import { CATEGORY_NAMES } from './readings/data.js';
import { WX_COLORS, WX_BG, getRelationClass, getVerdictClass } from './core.js';
import { SHICHEN_NAMES, SHICHEN_ELEMENTS } from './lunar.js';

const gColors = {daan:'var(--green)', liulian:'#5a4a3a', suxi:'var(--gold-dark)', chikou:'#c0392b', xiaoji:'var(--blue)', kongwang:'var(--purple)'};
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function sectionTitle(icon,title,desc=''){return `<div class="card-title"><span>${icon}</span><div><strong>${title}</strong>${desc?`<small>${desc}</small>`:''}</div></div>`;}
function palaceTrackCard(g,item,role,fin){ return `<div class="palace-card track-card gong-${g.pinyin} ${fin?'final':''}" ${fin?`style="border-color:${gColors[g.pinyin]}"`:''}><div class="palace-label">${esc(item.label)}</div><div class="palace-role">${esc(role)}</div><div class="palace-icon">${g.icon}</div><div class="palace-name">${g.name}</div><span class="palace-nature">${g.nature}</span><p class="palace-desc">${esc(item.text)}</p></div>`; }
function renderReportHeader(r){ return `<div class="report-topbar"><div><div class="report-kicker">本次问事 <span>${esc(r.categoryName)} · ${esc(r.verdict)}</span></div></div><div class="report-actions"><button id="saveResultBtn" class="ghost-btn">保存结果</button><button id="resetBtn" class="ghost-btn">重新起卦</button></div></div>`; }
function renderOverview(r){ return `<section class="overview-card result-section"><div class="overview-head"><div class="score-ring"><span>${r.score}</span><small>/5</small></div><div><div class="overline">${esc(r.categoryName)} · ${esc(r.verdict)}</div><div class="headline">${esc(r.headline)}</div><div class="keywords">${r.keywords.map(k=>`<span class="keyword">${esc(k)}</span>`).join('')}</div></div></div><p class="summary lead-summary">${esc(r.summary)}</p></section>`; }
function renderPalaceTrack(first,middle,final,r){ return `<section class="card result-section palace-track-section">${sectionTitle('📖','三宫轨迹','宫位、吉凶与解释合并展示，避免重复')}<div class="three-palaces">${palaceTrackCard(first,r.timeline[0],'第一宫',false)}${palaceTrackCard(middle,r.timeline[1],'第二宫',false)}${palaceTrackCard(final,r.timeline[2],'第三宫',true)}</div></section>`; }
function renderDetails(r){ if(r.category==='general') return `<section class="card result-section">${sectionTitle('🔮','专项提示','选择具体事项后显示分层判断')}<p class="summary">当前为综合模式，主要展示事情走势、关键提示与行动建议。选择“求财、婚恋、事业”等事项后，可查看更细的分层详断。</p></section>`; return `<section class="cat-reading result-section">${sectionTitle('🔮',`${esc(r.categoryName)}分层详断`,'按现状、阻力、转机、建议与应期拆解')}<div class="section-grid detail-grid">${r.detail.map((s,i)=>`<div class="reading-section"><span class="section-index">${i+1}</span><h4>${esc(s.title)}</h4><p>${esc(s.text)}</p></div>`).join('')}</div></section>`; }
function renderCombos(r){ if(!r.combos.length) return ''; return `<details class="card result-section compact-section process-card"><summary>🧩 查看传统象意依据</summary><div class="rule-stack">${r.combos.map((c,i)=>`<div class="analysis-section rule-item"><h4>${i===0?'整体走势':'阶段变化'} · ${esc(c.theme)}</h4><p>${esc(c.meaning)} ${esc(c.advice)}</p></div>`).join('')}</div></details>`; }
function relBlock(title,item){ return `<div class="analysis-section rule-item"><h4>${title}<span>${item.label}</span></h4><p>${esc(item.text)}</p></div>`; }
function renderWuxing(r,a,b,c){ return `<details class="card result-section compact-section process-card"><summary>🔥 查看五行关系</summary><div class="wuxing-row"><span class="wuxing-tag">${a.name} ${a.element}·${a.deity}</span><span class="wuxing-tag">${b.name} ${b.element}·${b.deity}</span><span class="wuxing-tag">${c.name} ${c.element}·${c.deity}</span></div>${relBlock(`${a.name} → ${b.name}`,r.wuxing.causeToProcess)}${relBlock(`${b.name} → ${c.name}`,r.wuxing.processToResult)}${relBlock(`${a.name} → ${c.name}`,r.wuxing.causeToResult)}</details>`; }
function renderShichen(info, final){ if(!info) return ''; const scEl = SHICHEN_ELEMENTS[info.index]; return `<details class="relation-card result-section compact-section process-card"><summary>⚖️ 查看时辰辅助</summary><div class="relation-header"><div class="relation-element"><span class="el-label">${SHICHEN_NAMES[info.index]}时</span><span class="el-value" style="color:${WX_COLORS[scEl]};border-color:${WX_COLORS[scEl]};background:${WX_BG[scEl]}">${scEl}</span></div><div class="relation-arrow">→</div><div class="relation-element"><span class="el-label">${final.name}</span><span class="el-value" style="color:${WX_COLORS[final.element]};border-color:${WX_COLORS[final.element]};background:${WX_BG[final.element]}">${final.element}</span></div></div><div class="relation-result ${getRelationClass(info.rel)}">${info.label}</div><div class="relation-detail">${esc(info.text)}</div></details>`; }
function renderAdvanced(r){ const a=r.advanced; if(!a) return ''; return `<section class="card result-section advanced-card">${sectionTitle('🧠','关键提示','把人物、应期、场景和方位合并成可操作线索')}<div class="insight-grid"><div class="insight-box"><h4>人物线索</h4><p>${esc(a.persona.main)} ${esc(a.persona.process)} ${esc(a.persona.tendency)}</p></div><div class="insight-box highlight"><h4>应期参考</h4><p>${esc(a.timing.pace)}：${esc(a.timing.window)}。${esc(a.timing.basis)}</p></div><div class="insight-box"><h4>场景线索</h4><p>${esc(a.location.direction)}；${esc(a.location.places.join('、'))}；相关物象：${esc(a.location.objects.join('、'))}；事项线索：${esc(a.location.hint)}。</p></div><div class="insight-box"><h4>六神提示</h4><p>${a.deity.map(x=>`【${x.stage}·${x.deity}】${x.symbol}`).join('；')}。</p></div></div></section>`; }
function renderAdvice(r){ return `<section class="card result-section advice-card">${sectionTitle('🧭','行动建议','最后按宜、忌、场景、人物线索收束')}<div class="advice-list"><div class="advice-box good"><h4>宜</h4><ul>${r.advice.suitable.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box warn"><h4>忌</h4><ul>${r.advice.avoid.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box"><h4>方位/场景</h4><ul><li>${esc(r.advice.direction)}</li></ul></div><div class="advice-box"><h4>人物线索</h4><ul><li>${esc(r.advice.people)}</li></ul></div></div></section>`; }
function renderProcess(processText){ return `<details class="card result-section process-card"><summary>📐 查看起卦过程</summary>${processText.map((t,i)=>`<div class="process-step">${'①②③'[i]} ${esc(t)}</div>`).join('')}</details>`; }
export function renderResults({first,middle,final,processText,report,scInfo}){ let h='<div id="results" class="report-content">'; h+=renderReportHeader(report)+renderOverview(report)+renderPalaceTrack(first,middle,final,report); h+=renderDetails(report)+renderAdvanced(report)+renderAdvice(report)+renderCombos(report)+renderWuxing(report,first,middle,final)+renderShichen(scInfo,final)+renderProcess(processText); h+='</div>'; document.getElementById('results').outerHTML=h; }
export function renderCategoryButtons(active='general'){ return Object.entries(CATEGORY_NAMES).map(([key,name])=>`<button class="cat-btn ${key===active?'active':''}" data-cat="${key}">${name}</button>`).join(''); }
