import { CATEGORY_NAMES } from './readings/data.js';
import { WX_COLORS, WX_BG, getRelationClass, getVerdictClass } from './core.js';
import { SHICHEN_NAMES, SHICHEN_ELEMENTS } from './lunar.js';

const gColors = {daan:'var(--green)', liulian:'#5a4a3a', suxi:'var(--gold-dark)', chikou:'#c0392b', xiaoji:'var(--blue)', kongwang:'var(--purple)'};
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function pCard(g,label,role,fin){ return `<div class="palace-card gong-${g.pinyin} ${fin?'final':''}" ${fin?`style="border-color:${gColors[g.pinyin]}"`:''}><div class="palace-label">${label}</div><div class="palace-role">${role}</div><div class="palace-icon">${g.icon}</div><div class="palace-name">${g.name}</div><span class="palace-nature">${g.nature}</span></div>`; }
function renderOverview(r){ return `<div class="overview-card"><div class="overview-head"><div class="score-ring">${r.score}/5</div><div><div class="headline">${esc(r.headline)}</div><div class="keywords">${r.keywords.map(k=>`<span class="keyword">${esc(k)}</span>`).join('')}</div></div></div><div class="verdict ${getVerdictClass(r.verdict)}">${esc(r.categoryName)} · ${esc(r.verdict)}</div><p class="summary">${esc(r.summary)}</p></div>`; }
function renderTimeline(r){ return `<div class="card"><div class="card-title">📖 三宫轨迹</div><div class="timeline">${r.timeline.map(x=>`<div class="timeline-item"><h4>${x.label} · ${x.palace}</h4><p>${esc(x.text)}</p></div>`).join('')}</div></div>`; }
function renderDetails(r){ if(r.category==='general') return `<div class="card"><div class="card-title">🔮 各事项速查</div><p class="summary">选择“求财、婚恋、事业”等具体事项后，可查看分层详断。当前综合模式主要展示三宫、组合与五行趋势。</p></div>`; return `<div class="cat-reading"><h3>🔮 ${esc(r.categoryName)}分层详断</h3><div class="section-grid">${r.detail.map(s=>`<div class="reading-section"><h4>${esc(s.title)}</h4><p>${esc(s.text)}</p></div>`).join('')}</div></div>`; }
function renderCombos(r){ if(!r.combos.length) return ''; return `<div class="card"><div class="card-title">🧩 组合象意</div>${r.combos.map(c=>`<div class="analysis-section"><h4>▸ ${esc(c.theme)}</h4><p>${esc(c.meaning)} ${esc(c.advice)}</p></div>`).join('')}</div>`; }
function relBlock(title,item){ return `<div class="analysis-section"><h4>▸ ${title}：${item.label}</h4><p>${esc(item.text)}</p></div>`; }
function renderWuxing(r,a,b,c){ return `<div class="card"><div class="card-title">🔥 五行与六神</div><div class="wuxing-row"><span class="wuxing-tag">${a.name} ${a.element}·${a.deity}</span><span class="wuxing-tag">${b.name} ${b.element}·${b.deity}</span><span class="wuxing-tag">${c.name} ${c.element}·${c.deity}</span></div>${relBlock(`${a.name}→${b.name}`,r.wuxing.causeToProcess)}${relBlock(`${b.name}→${c.name}`,r.wuxing.processToResult)}${relBlock(`${a.name}→${c.name}`,r.wuxing.causeToResult)}</div>`; }
function renderShichen(info, final){ if(!info) return ''; const scEl = SHICHEN_ELEMENTS[info.index]; return `<div class="relation-card"><div class="card-title">⚖️ 时辰与落宫生克</div><div class="relation-header"><div class="relation-element"><span class="el-label">${SHICHEN_NAMES[info.index]}时</span><span class="el-value" style="color:${WX_COLORS[scEl]};border-color:${WX_COLORS[scEl]};background:${WX_BG[scEl]}">${scEl}</span></div><div class="relation-arrow">→</div><div class="relation-element"><span class="el-label">${final.name}</span><span class="el-value" style="color:${WX_COLORS[final.element]};border-color:${WX_COLORS[final.element]};background:${WX_BG[final.element]}">${final.element}</span></div></div><div class="relation-result ${getRelationClass(info.rel)}">${info.label}</div><div class="relation-detail">${esc(info.text)}</div></div>`; }
function renderAdvanced(r){ const a=r.advanced; if(!a) return ''; return `<div class="card"><div class="card-title">🧠 高级推理</div><div class="section-grid"><div class="reading-section"><h4>六神推理</h4><p>${a.deity.map(x=>`【${x.stage}·${x.deity}】${x.symbol}`).join('；')}。</p></div><div class="reading-section"><h4>动态应期</h4><p>${esc(a.timing.pace)}：${esc(a.timing.window)}。${esc(a.timing.basis)}</p></div><div class="reading-section"><h4>人物画像</h4><p>${esc(a.persona.main)} ${esc(a.persona.process)} ${esc(a.persona.tendency)}</p></div><div class="reading-section"><h4>方位场景</h4><p>${esc(a.location.direction)}；${esc(a.location.places.join('、'))}；相关物象：${esc(a.location.objects.join('、'))}；事项线索：${esc(a.location.hint)}。</p></div></div></div>`; }
function renderAdvice(r){ return `<div class="card"><div class="card-title">🧭 应对建议与线索</div><div class="advice-list"><div class="advice-box"><h4>宜</h4><ul>${r.advice.suitable.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box"><h4>忌</h4><ul>${r.advice.avoid.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box"><h4>方位/场景</h4><ul><li>${esc(r.advice.direction)}</li></ul></div><div class="advice-box"><h4>人物线索</h4><ul><li>${esc(r.advice.people)}</li></ul></div></div></div>`; }
export function renderResults({first,middle,final,processText,report,scInfo}){ let h='<div id="results">'; h+=`<div class="three-palaces">${pCard(first,'第一宫','起因·背景',false)}${pCard(middle,'第二宫','经过·发展',false)}${pCard(final,'第三宫','结果·现状',true)}</div>`; h+=renderOverview(report); h+=`<div class="card"><div class="card-title">📐 推算过程</div>${processText.map((t,i)=>`<div class="process-step">${'①②③'[i]} ${esc(t)}</div>`).join('')}</div>`; h+=renderShichen(scInfo,final)+renderTimeline(report)+renderDetails(report)+renderCombos(report)+renderAdvanced(report)+renderWuxing(report,first,middle,final)+renderAdvice(report); h+='</div>'; document.getElementById('results').outerHTML=h; }
export function renderCategoryButtons(active='general'){ return Object.entries(CATEGORY_NAMES).map(([key,name])=>`<button class="cat-btn ${key===active?'active':''}" data-cat="${key}">${name}</button>`).join(''); }
