import { CATEGORY_NAMES } from './readings/data.js';
import { WX_COLORS, WX_BG, getRelationClass, getVerdictClass } from './core.js';
import { SHICHEN_NAMES, SHICHEN_ELEMENTS } from './lunar.js';

const gColors = {daan:'var(--green)', liulian:'#5a4a3a', suxi:'var(--gold-dark)', chikou:'#c0392b', xiaoji:'var(--blue)', kongwang:'var(--purple)'};
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function pCard(g,label,role,fin){ return `<div class="palace-card gong-${g.pinyin} ${fin?'final':''}" ${fin?`style="border-color:${gColors[g.pinyin]}"`:''}><div class="palace-label">${label}</div><div class="palace-role">${role}</div><div class="palace-icon">${g.icon}</div><div class="palace-name">${g.name}</div><span class="palace-nature">${g.nature}</span></div>`; }
function sectionTitle(icon,title,desc=''){return `<div class="card-title"><span>${icon}</span><div><strong>${title}</strong>${desc?`<small>${desc}</small>`:''}</div></div>`;}
function renderOverview(r){ return `<section class="overview-card result-section"><div class="overview-head"><div class="score-ring"><span>${r.score}</span><small>/5</small></div><div><div class="overline">${esc(r.categoryName)} · ${esc(r.verdict)}</div><div class="headline">${esc(r.headline)}</div><div class="keywords">${r.keywords.map(k=>`<span class="keyword">${esc(k)}</span>`).join('')}</div></div></div><p class="summary lead-summary">${esc(r.summary)}</p></section>`; }
function renderTimeline(r){ return `<section class="card result-section">${sectionTitle('📖','三宫路径','先看事情如何从起因走到结果')}<div class="timeline">${r.timeline.map(x=>`<div class="timeline-item"><div class="timeline-label">${x.label}</div><h4>${x.palace}</h4><p>${esc(x.text)}</p></div>`).join('')}</div></section>`; }
function renderDetails(r){ if(r.category==='general') return `<section class="card result-section">${sectionTitle('🔮','专项详断','选择具体事项后显示分层判断')}<p class="summary">当前为综合模式，主要展示三宫路径、组合规则、五行关系与高级推理。选择“求财、婚恋、事业”等事项后，可查看更细的分层详断。</p></section>`; return `<section class="cat-reading result-section">${sectionTitle('🔮',`${esc(r.categoryName)}分层详断`,'按事项拆解现状、阻力、转机、建议与应期')}<div class="section-grid detail-grid">${r.detail.map((s,i)=>`<div class="reading-section"><span class="section-index">${i+1}</span><h4>${esc(s.title)}</h4><p>${esc(s.text)}</p></div>`).join('')}</div></section>`; }
function renderCombos(r){ if(!r.combos.length) return ''; return `<section class="card result-section compact-section">${sectionTitle('🧩','组合依据','三宫整体格局与两段转化规则')}<div class="rule-stack">${r.combos.map((c,i)=>`<div class="analysis-section rule-item"><h4>${i===0?'总格局':'转化'} · ${esc(c.theme)}</h4><p>${esc(c.meaning)} ${esc(c.advice)}</p></div>`).join('')}</div></section>`; }
function relBlock(title,item){ return `<div class="analysis-section rule-item"><h4>${title}<span>${item.label}</span></h4><p>${esc(item.text)}</p></div>`; }
function renderWuxing(r,a,b,c){ return `<section class="card result-section compact-section">${sectionTitle('🔥','五行校验','用于判断前后是否相生、相克、泄气或受制')}<div class="wuxing-row"><span class="wuxing-tag">${a.name} ${a.element}·${a.deity}</span><span class="wuxing-tag">${b.name} ${b.element}·${b.deity}</span><span class="wuxing-tag">${c.name} ${c.element}·${c.deity}</span></div>${relBlock(`${a.name} → ${b.name}`,r.wuxing.causeToProcess)}${relBlock(`${b.name} → ${c.name}`,r.wuxing.processToResult)}${relBlock(`${a.name} → ${c.name}`,r.wuxing.causeToResult)}</section>`; }
function renderShichen(info, final){ if(!info) return ''; const scEl = SHICHEN_ELEMENTS[info.index]; return `<section class="relation-card result-section compact-section">${sectionTitle('⚖️','时辰辅助','当前时辰五行与最终落宫的关系')}<div class="relation-header"><div class="relation-element"><span class="el-label">${SHICHEN_NAMES[info.index]}时</span><span class="el-value" style="color:${WX_COLORS[scEl]};border-color:${WX_COLORS[scEl]};background:${WX_BG[scEl]}">${scEl}</span></div><div class="relation-arrow">→</div><div class="relation-element"><span class="el-label">${final.name}</span><span class="el-value" style="color:${WX_COLORS[final.element]};border-color:${WX_COLORS[final.element]};background:${WX_BG[final.element]}">${final.element}</span></div></div><div class="relation-result ${getRelationClass(info.rel)}">${info.label}</div><div class="relation-detail">${esc(info.text)}</div></section>`; }
function renderAdvanced(r){ const a=r.advanced; if(!a) return ''; return `<section class="card result-section advanced-card">${sectionTitle('🧠','高级推理','六神、应期、人物与方位的综合提示')}<div class="insight-grid"><div class="insight-box"><h4>六神推理</h4><p>${a.deity.map(x=>`【${x.stage}·${x.deity}】${x.symbol}`).join('；')}。</p></div><div class="insight-box highlight"><h4>动态应期</h4><p>${esc(a.timing.pace)}：${esc(a.timing.window)}。${esc(a.timing.basis)}</p></div><div class="insight-box"><h4>人物画像</h4><p>${esc(a.persona.main)} ${esc(a.persona.process)} ${esc(a.persona.tendency)}</p></div><div class="insight-box"><h4>方位场景</h4><p>${esc(a.location.direction)}；${esc(a.location.places.join('、'))}；相关物象：${esc(a.location.objects.join('、'))}；事项线索：${esc(a.location.hint)}。</p></div></div></section>`; }
function renderAdvice(r){ return `<section class="card result-section advice-card">${sectionTitle('🧭','行动建议','最后按宜、忌、场景、人物线索收束')}<div class="advice-list"><div class="advice-box good"><h4>宜</h4><ul>${r.advice.suitable.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box warn"><h4>忌</h4><ul>${r.advice.avoid.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="advice-box"><h4>方位/场景</h4><ul><li>${esc(r.advice.direction)}</li></ul></div><div class="advice-box"><h4>人物线索</h4><ul><li>${esc(r.advice.people)}</li></ul></div></div></section>`; }
function renderProcess(processText){ return `<details class="card result-section process-card"><summary>📐 查看推算过程</summary>${processText.map((t,i)=>`<div class="process-step">${'①②③'[i]} ${esc(t)}</div>`).join('')}</details>`; }
export function renderResults({first,middle,final,processText,report,scInfo}){ let h='<div id="results">'; h+=renderOverview(report); h+=`<div class="three-palaces">${pCard(first,'第一宫','起因·背景',false)}${pCard(middle,'第二宫','经过·发展',false)}${pCard(final,'第三宫','结果·现状',true)}</div>`; h+=renderTimeline(report)+renderDetails(report)+renderAdvanced(report)+renderCombos(report)+renderWuxing(report,first,middle,final)+renderShichen(scInfo,final)+renderAdvice(report)+renderProcess(processText); h+='</div>'; document.getElementById('results').outerHTML=h; }
export function renderCategoryButtons(active='general'){ return Object.entries(CATEGORY_NAMES).map(([key,name])=>`<button class="cat-btn ${key===active?'active':''}" data-cat="${key}">${name}</button>`).join(''); }
